version: "3"

silent: true

tasks:
  default:
    cmd: task --list

  run:
    desc: Run the webapp
    cmd: clojure -M:main

  clean:
    desc: Remove generated code
    cmd: rm -rf target

  lint:
    desc: Lint code using clj-kondo
    cmd: rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

  build:
    desc: Build production uberjar
    cmd: clojure -T:build uberjar

  repl:
    desc: Run a project REPL
    cmd: clj -M:dev:test

  test:
    desc: Run unit tests
    cmd: clojure -X:test

  test:watch:
    desc: Watch source code and run tests accordingly
    cmd: clojure -X:test:watcher
