tap "borkdude/brew"
tap "clojure/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "editorconfig"
brew "just"

brew "borkdude/brew/clj-kondo"
brew "clojure/tools/clojure"

cask "temurin11"
