jarfile := "{{artifact/id}}.jar"

default:
    @just --list

run:
    @clojure -M:main

clean:
    @-rm -rf {{ jarfile }}

lint:
    @rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

build:
    @clojure -M:uberjar --target {{ jarfile }}

repl:
    @clj -M:dev:test

test:
    @clojure -M:test:runner

watch-test:
    @clojure -M:test:watcher

run-jar: build
    @java -jar {{ jarfile }} -m {{raw-name/ns}}.app
