jarfile := "{{artifact/id}}.jar"

default:
	@just --list

run:
	@clojure -M:main

clean:
	@-rm -rf {{jarfile}}

lint:
	@clj-kondo --lint src dev test

build:
	@clojure -M:uberjar --target {{jarfile}}

repl:
	@clj -M:dev:test

test:
	@clojure -M:test:runner

autotest:
	@clojure -M:test:watcher

run-jar: build
	@java -cp {{jarfile}} clojure.main -m {{raw-name/ns}}.app
