default:
    @just --list

run:
    @clojure -M:main

clean:
    @-rm -rf target

lint:
    @rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

build:
    @clojure -T:build uberjar

repl:
    @clj -M:dev:test

test:
    @clojure -M:test:runner

watch-test:
    @clojure -M:test:watcher
